version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/GraphTutorial"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
